name: CDK Nag Scan

on:
  pull_request:
    branches: [ main ]

jobs:
  cdk_nag_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Synthesize CDK app
        run: npx cdk synth

      - name: Run CDK Nag
        run: npx cdk-nag --fail-on-warnings # cdk-nag will be added to package.json later
